os:
  - linux

language: php

php:
  - '7.2'
  
before_script:
  - composer self-update
  - composer install --no-interaction
  - cp .env.travis .env
  - phpenv rehash
  
script:
  - vendor/bin/phpunit
